# Generated by Django 6.1.1 on 2026-09-07 14:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('T3', 'T-3 Days Alert'), ('T1', 'T-1 Day Alert'), ('OVERDUE', 'Overdue Alert')], max_length=20)),
                ('cycle_due_date', models.DateField(help_text='The next_due date for which this alert was triggered')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='maintenance.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'alert_type', 'cycle_due_date'), name='unique_alert_per_cycle')],
            },
        ),
    ]
